version: '3.8'
services:
  front-end:
    # container_name: front-end
    image: front-end:v1
    build: ./front-end
    networks: 
      - proj-net
    deploy:
      replicas: 3
  rand-name-gen:
    container_name: rand-name-gen
    image: name-generator:v1
    build: ./rand-name-gen
    networks: 
      - proj-net
  rand-num-gen:
    container_name: rand-num-gen
    image: num-generator:v1
    build: ./rand-num-gen
    networks: 
      - proj-net
  race-gen:
    container_name: race-gen
    image: race-generator:v1
    build: ./race-gen
    networks: 
      - proj-net
  nginx:
    container_name: nginx
    image: nginx:latest
    networks:
      - proj-net
    volumes:
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/nginx.conf
    ports:
      - target: 80
        published: 80
        protocol: tcp
    # depends_on:
    #   - front-end
networks:
  proj-net:
    driver: overlay
